#Configuration for System FRU type 1
fruConf["Product Manufacturer"]="system-manufacturer"
fruConf["Product Name"]="system-product-name"
fruConf["Product Serial"]="system-serial-number"
fruConf["Product Asset Tag"]="baseboard-asset-tag"
fruConf["Product Part Number"]="system-version"
fruConf["Product Extra"]="system-sku-number"
fruConf["Board Mfg"]="baseboard-manufacturer"
fruConf["Board Product"]="baseboard-product-name"
fruConf["Board Serial"]="baseboard-serial-number"
fruConf["Board Part Number"]="baseboard-version"
fruConf["Board Extra"]="system-sku-number"
fruConf["Chassis Serial"]="system-serial-number"
fruConf["Chassis Part Number"]="system-version"
fruConf["Chassis Extra-1"]="chassis-asset-tag"
fruConf["Chassis Extra-3"]="chassis-manufacturer"
fruConf["Chassis Extra-2"]="system-uuid"